### ISSUE TITLE
Identify browser support and make it consistent

### ISSUE THREAD

**Issue by averyvery** [awavering/trackomatic#15]
Some features work in legacy browsers, some don't. We should standardize on this and make sure that all features meet the same requirement.

**Comment by averyvery** [comment]
cc @solomonhawk

**Comment by solomonhawk** [comment]
I'm going to approach this with IE9 support in mind. If we want to we could create a separate trackomatic-legacy bundle that gets generated by the build for targeting IE8 support projects.

**Comment by awavering** [comment]
:+1:

**Comment by averyvery** [comment]
@solomonhawk in this case, does it make sense to just wrap the whole thing in...

```
if('querySelector' in document
     && 'localStorage' in window
     && 'addEventListener' in window) {
       ...
     }
```

...or just individual features?

**Comment by solomonhawk** [comment]
Yes we should just use that, good idea Doug.

**Comment by solomonhawk** [comment]
I implemented the mustard-cutting technique discussed here in 1.1.1.

**Comment by awavering** [comment]
Thanks @solomonhawk. Sounds like we're good to close this?

**Comment by averyvery** [comment]
Closing this.
