### ISSUE TITLE
Resolve hosting concerns

### ISSUE THREAD

**Issue by averyvery** [awavering/trackomatic#16]
We need to hash out how/where to host this file so it's not being served from vigesharing-is-vigecaring/awavering and it's being appropriately gzipped/cached. A dev might be needed to get us up and running on something; they know more about what accounts we have access to/would be best.

**Comment by averyvery** [comment]
cc @ltk

**Comment by solomonhawk** [comment]
Right now we're on S3 / CloudFront. @brianjlandau had said that https://www.jsdelivr.com/ might be worth looking at.

**Comment by awavering** [comment]
https://www.jsdelivr.com/ looks great :+1:

**Comment by averyvery** [comment]
Did we get this? I thought we got this.

**Comment by averyvery** [comment]
nevermind me, literally talking about this now.

**Comment by solomonhawk** [comment]
For the time being we are sticking with S3 + CloudFront.
