### ISSUE TITLE
Set up docs and releases

### ISSUE THREAD

**Issue by averyvery** [awavering/trackomatic#18]
We should talk about how GitHub releases work, and how they interact with the Changelog. We should also probably tweak CONTRIBUTING.md so it reflects the project more specifically.

**Comment by solomonhawk** [comment]
https://github.com/vigetlabs/trackomatic/pull/25 begins to address this but really there needs to be more discussion first.

**Comment by solomonhawk** [comment]
This has been more fully fleshed out in `1.1.1`.
