### ISSUE TITLE
Wordpress Integration

### ISSUE THREAD

**Issue by vilbht** [awavering/trackomatic#27]
Hello,

Any tips on the best way to use & optimize Trackomatic for use with Wordpress?

Thanks'

**Comment by awavering** [comment]
Good question, Vilav. If you're familiar with Wordpress's header templates, you can modify the regular Google Analytics snippet with the instructions from the [readme](https://github.com/vigetlabs/trackomatic#installation) and install that in your header template.

If you're using a plugin to handle Google Analytics, the ability to install Trackomatic depends on the amount of flexibility in the plugin.

**Comment by vilbht** [comment]
@awavering Thank you Albert! Will follow those instructions and try the installation!

Is there a Google Analytics dashboard that goes with the plugin? Since the plugin tracks a wide variety of parameters, is there a more optimized dashboard that can prominently bring the reporting of these parameters to the forefront?

**Comment by awavering** [comment]
Glad you asked! The [Technical Performance Dashboard](https://www.google.com/analytics/gallery/#posts/search/%3F_.tab%3DMy%26_.sort%3DDATE%26_.start%3D0%26_.viewId%3DsJXXMwZtSCmLNYXy-gmozA/) exposes some of the custom events that are generated by Trackomatic. Other [events](https://github.com/vigetlabs/trackomatic#custom-events) follow an intuitive Category/Action/Label standard that should make sense if you dig into your GA Event report. Let me know if you're having trouble pulling a particular event into a dashboard and I can help you out as well.
